### ISSUE TITLE
Render error in nullsafe TextoneLine inside IntrinsicHeight widget

### ISSUE THREAD

**Issue by erickok** [marcglasberg/assorted_layout_widgets#10]
When using assorted_layout_widgets 4.0.0 (with nullsafety) and wrapping a `TextOneLine` widget in a `IntrinsicHeight` widget, I get a rendering error.

```
IntrinsicHeight(child: TextOneLine("test this widget"))
```

produces:

```
The following _CastError was thrown during performLayout():
type 'List<PlaceholderDimensions?>' is not a subtype of type 'List<PlaceholderDimensions>?' in type
cast

The relevant error-causing widget was:
  IntrinsicHeight
  file:///Users/erickok/Dev/vrt/flutter-article-components/lib/components/player_time_line_event_component.dart:57:27

When the exception was thrown, this was the stack:
#0      RenderParagraphX._computeChildrenHeightWithMinIntrinsics (package:assorted_layout_widgets/src/text_one_line.dart:586:65)
#1      RenderParagraphX._computeIntrinsicHeight (package:assorted_layout_widgets/src/text_one_line.dart:475:5)
#2      RenderParagraphX.computeMaxIntrinsicHeight (package:assorted_layout_widgets/src/text_one_line.dart:487:12)
#3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1377:23)
#4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1375:42)
#6      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1747:12)
#7      RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> 
```

This is because the code here tried to force-cast a non-nullable list of nullable PlaceholderDimensions into a nullable list of non-nullable PlaceholderDimensions.

**Comment by marcglasberg** [comment]
Thanks for the PR.
